"""add_indexes_for_hot_path_queries

Revision ID: 079042331967
Revises: ea53de92707b
Create Date: 2026-05-02 13:01:16.036204

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '079042331967'
down_revision: Union[str, None] = 'ea53de92707b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_match_assignments_hazard_event_id'), 'match_assignments', ['hazard_event_id'], unique=False)
    op.create_index(op.f('ix_match_assignments_user_id'), 'match_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_respondent_profiles_availability_status'), 'respondent_profiles', ['availability_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respondent_profiles_availability_status'), table_name='respondent_profiles')
    op.drop_index(op.f('ix_match_assignments_user_id'), table_name='match_assignments')
    op.drop_index(op.f('ix_match_assignments_hazard_event_id'), table_name='match_assignments')
    # ### end Alembic commands ###
