"""add_trust_tier_and_communication_modes_to_respondent_profiles

Revision ID: fa4369716818
Revises: 079042331967
Create Date: 2026-05-02 14:07:41.569296

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'fa4369716818'
down_revision: Union[str, None] = '079042331967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('respondent_profiles', sa.Column('trust_tier', sa.Integer(), nullable=False))
    op.add_column('respondent_profiles', sa.Column('communication_modes', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('respondent_profiles', 'communication_modes')
    op.drop_column('respondent_profiles', 'trust_tier')
    # ### end Alembic commands ###
